server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/product
    username: root
    password: password

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#logging:
#  level:
#    org:
#      hibernate: trace



